apiVersion: v1
kind:  Pod
metadata:
  name: environment
  labels:
    project: expense
    module: backend
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: Devops
    - name: duration
      value: 120hrs
    - name: trainer
      value: Sivakumar