apiVersion: v1
kind: Service
metadata:
  name: clusterIP
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-servies
    protocal: TCP
    port: 80
    targetPort: 80
  
